aemsites/vitamix

blocks/hero/hero.css
Test URLs:
- Before: https://main--vitamix--aemsites.aem.page/us/en_us/why-vitamix
- After: https://hero--vitamix--aemsites.aem.page/us/en_us/why-vitamix
=> fix: desktop hero

blocks/banner/banner.css, blocks/cards/cards.css, blocks/carousel/carousel.css, blocks/carousel/carousel.js
https://blocks--vitamix--aemsites.aem.page/us/en_us/why-vitamix
=> chore: some more blocks

blocks/carousel/carousel.css, blocks/carousel/carousel.js
https://carousel-expansion--vitamix--aemsites.aem.live/us/en_us/why-vitamix
=> chore: carousel-expansion

blocks/carousel/carousel.css, blocks/carousel/carousel.js
https://carousel-exp--vitamix--aemsites.aem.live/
=> chore: re-add carousel expansion

blocks/header/header.css, blocks/header/header.js, blocks/hero/hero.css, styles/colors.css, styles/styles.css, styles/typography.css
https://visual-tweaks--vitamix--aemsites.aem.live/
=> chore: visual tweaks for above the fold desktop

scripts/scripts.js, styles/styles.css
- After: https://better-bg--vitamix--aemsites.aem.live/us/en_us/why-vitamix
=> chore: improve section background image quality and responsive loading

blocks/banner/banner.css, styles/styles.css
- After: https://inset-spacing--vitamix--aemsites.aem.live/us/en_us/why-vitamix
=> chore: banner inset spacing

blocks/form/form.css, blocks/form/form.js, blocks/header/header.css, blocks/header/header.js, styles/styles.css
https://cart-account--vitamix--aemsites.aem.live/
set cookies:
vitamix_customer_name: <name>
cart_item_count: <number>
=> chore: cart and account decoration

blocks/banner/banner.css, blocks/cards/cards.css, blocks/carousel/carousel.css, blocks/footer/footer.css, blocks/header/header.css, blocks/hero/hero.css, styles/styles.css
- After: https://body-bg--vitamix--aemsites.aem.live/us/en_us/why-vitamix
=> chore: change z-index to allow for body-bg

blocks/navigation/navigation.css, blocks/navigation/navigation.js, styles/styles.css
https://jump-nav--vitamix--aemsites.aem.live/us/en_us/why-vitamix
=> chore: initial jump nav

blocks/navigation/navigation.css, blocks/navigation/navigation.js
https://jump-nav--vitamix--aemsites.aem.live/us/en_us/why-vitamix
=> chore: styling

blocks/header/header.js
rewrite nav for `.vitamix.com` hosts.
- Before: https://main--vitamix--aemsites.aem.live/
- After: https://rewrite-nav--vitamix--aemsites.aem.live/
=> chore: rewrite nav when needed

blocks/navigation/navigation.css, blocks/navigation/navigation.js
https://mobile-jump-nav--vitamix--aemsites.aem.live/us/en_us/why-vitamix
=> chore: mobile jump nav

blocks/banner/banner.css
- After: https://banner-image--vitamix--aemsites.aem.live/us/en_us/why-vitamix
=> chore: banner image tune-up

blocks/modal/modal.css, blocks/modal/modal.js, scripts/scripts.js
https://nav-modal--vitamix--aemsites.aem.live/
=> chore: nav modal

blocks/header/header.js
- After: https://cart-items--vitamix--aemsites.aem.live/us/en_us/why-vitamix
```
document.cookie = "cart_items_count=2";
location.reload();
```
vs.
```
document.cookie = "cart_items_count=0";
location.reload();
```
=> chore: don't show cart items if 0

blocks/modal/modal.css
better responsive behavior, bigger size modal.
- After: https://sign-up-mod--vitamix--aemsites.aem.live/us/en_us/why-vitamix
=> chore: signup mods

blocks/banner/banner.js, blocks/carousel/carousel.js, blocks/hero/hero.js
- After: https://ios-autoplay--vitamix--aemsites.aem.live/us/en_us/why-vitamix
=> iOS autoplay

blocks/cards/cards.css
- After: https://cards-ko-font--vitamix--aemsites.aem.live/us/en_us/why-vitamix
=> chore: adjust cards knockout font weight

blocks/carousel/carousel.css, blocks/carousel/carousel.js
Test URLs:
- After: https://exp-caro--vitamix--aemsites.aem.live/us/en_us/why-vitamix
=> fix: expansion carousel button placement, spacing, autoplay

blocks/cards/cards.js, head.html, scripts/scripts.js, ue/scripts/ue.js
Don't merge the head.html change, as this is only temp.
Test URLs:
- Before: https://main--vitamix--aemsites.aem.live/
- After: https://ue--vitamix--aemsites.aem.live/
=> UE improvements

blocks/banner/banner.js, blocks/hero/hero.js, scripts/scripts.js
Test URLs:
- After: https://video--vitamix--aemsites.aem.live/us/en_us/why-vitamix
=> feat: buildVideo

blocks/banner/banner.js, blocks/carousel/carousel.css, blocks/carousel/carousel.js, blocks/hero/hero.js, scripts/scripts.js, styles/styles.css
⚠️  this will require an immediate content change to `why-vitamix` after merge
Test URLs:
- After: https://testimonial--vitamix--aemsites.aem.live/us/en_us/drafts/fkakatie/why-vitamix
=> Testimonial

component-models.json, ue-template.html, ue/models/blocks/cards.json
Add cards block options for UE
Test URLs:
- Before: https://main--vitamix--aemsites.aem.live/
- After: https://ue-updates--vitamix--aemsites.aem.live/
=> UE updates

scripts/consented.js, scripts/delayed.js, scripts/scripts.js
https://martech-cleanup--vitamix--aemsites.aem.live/us/en_us/why-vitamix
=> martech cleanup and consent gated martech loading

blocks/pdp/gallery.js, blocks/pdp/options.js, blocks/pdp/pdp.js, scripts/scripts.js
Test URLs:
- Before: https://pdp--vitamix--aemsites.aem.live/us/en_us/shop/ascent-x2?12kkkkk
- After: https://pdp-use-dom--vitamix--aemsites.aem.live/us/en_us/shop/ascent-x2?12kkkkk
=> fix: pull variants out of DOM instead of jsonld

.env, blocks/pdp/gallery.js, blocks/pdp/options.js, blocks/pdp/pdp.css, blocks/pdp/pdp.js, blocks/pdp/specification-tabs.js, scripts/scripts.js
Fixes rendering of simple, configurable and bundle products
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/products/ascent-x5
- After: https://product-types--vitamix--aemsites.aem.network/us/en_us/products/ascent-x5
=> fix: rendering of simple, configurable and bundle

blocks/pdp/pdp.css, blocks/pdp/pdp.js
fix #69 
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/products/7500
- After: https://pdp-faq-links--vitamix--aemsites.aem.network/us/en_us/products/7500
=> fix: pdp faq links

blocks/pdp/pdp.css, blocks/pdp/pdp.js
1. Fixes grid issues.
2. Moved `faq` and `reviews` element into `pdp-wrapper`.
3. Fix formatting of product descriptions that use `dl` and `dd`.
Fix #84
Test URLs:
- Before: https://main--vitamix--aemsites.aem.live/us/en_us/products/7500
- After: https://fix-84--vitamix--aemsites.aem.live/us/en_us/products/7500
=> fix: move faq and reviews into pdp wrapper. fix grid

blocks/pdp/pdp.css, blocks/pdp/pdp.js, blocks/pdp/specification-tabs.js
Fix #65
Test URLs:
https://product-content--vitamix--aemsites.aem.network/us/en_us/products/a3500-entertaining-bundle
https://product-content--vitamix--aemsites.aem.network/us/en_us/products/propel-series-750
https://product-content--vitamix--aemsites.aem.network/us/en_us/products/ascent-x2
=> chore: product content fragment

blocks/pdp/pdp.js, scripts/authentication/README.md, scripts/authentication/api.js, scripts/minicart/README.md, scripts/minicart/api.js, scripts/minicart/cart.js, scripts/minicart/util.js, scripts/storage/README.md, scripts/storage/util.js
Test URLs:
- After: https://lumabridge--vitamix--aemsites.aem.network/
=> feat: add lumabridge code

scripts/minicart/cart.js
Test URLs:
- After: https://lumabridge--vitamix--aemsites.aem.network/
=> fix: ignore auth for now

blocks/pdp/pdp.js
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/products/7500?color=white
- After: https://data-model-update--vitamix--aemsites.aem.network/us/en_us/products/7500?color=white
=> chore: adjust data model changes

blocks/pdp/options.js, blocks/pdp/pdp.css, blocks/pdp/pdp.js, scripts/scripts.js
Fix #101 
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/products/a2300?color=slate
- After: https://oos-options--vitamix--aemsites.aem.network/us/en_us/products/a2300?color=slate
=> chore: oos-options

blocks/pdp/options.js, scripts/scripts.js
Fix #111 
Test URLs:
- Before: 
https://main--vitamix--aemsites.aem.network/us/en_us/products/propel-series-510
https://main-variants--vitamix--aemsites.aem.network/us/en_us/products/e310
https://main-variants--vitamix--aemsites.aem.network/us/en_us/products/e310-and-pca-bundle
- After: 
https://imagelss-variants--vitamix--aemsites.aem.network/us/en_us/products/propel-series-510
https://imagelss-variants--vitamix--aemsites.aem.network/us/en_us/products/e310
https://imagelss-variants--vitamix--aemsites.aem.network/us/en_us/products/e310-and-pca-bundle
https://imagelss-variants--vitamix--aemsites.aem.network/us/en_us/products/ascent-x2
https://imagelss-variants--vitamix--aemsites.aem.network/us/en_us/products/a2300
https://imagelss-variants--vitamix--aemsites.aem.network/us/en_us/products/75 …
=> chore: imageless variants

blocks/pdp/gallery.css, blocks/pdp/gallery.js, blocks/video/video.js
Fix #118 
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/products/ascent-x2
- After: https://gallery-video--vitamix--aemsites.aem.network/us/en_us/products/ascent-x2
=> chore: add video

blocks/pdp/gallery.js, blocks/pdp/pdp.js, blocks/pdp/pricing.js
Test URLs:
- Before: 
https://main--vitamix--aemsites.aem.network/us/en_us/products/certified-reconditioned-a3500
https://main--vitamix--aemsites.aem.network/us/en_us/products/ascent-x2
- After: 
https://save-now--vitamix--aemsites.aem.network/us/en_us/products/certified-reconditioned-a3500
https://save-now--vitamix--aemsites.aem.network/us/en_us/products/ascent-x2
=> chore: save now

blocks/pdp/pdp.js
Fix #129 
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/products/ascent-x5-smartprep-kitchen-system
- After: https://details-links--vitamix--aemsites.aem.network/us/en_us/products/ascent-x5-smartprep-kitchen-system
=> chore: remove button styling

blocks/modal/modal.css, blocks/modal/modal.js, blocks/pdp/pdp.js, styles/colors.css, styles/styles.css
Test URLs:
- After: https://compare--vitamix--aemsites.aem.network/
=> feat: add to compare

blocks/cards/cards.css, blocks/cards/cards.js
updated card styling to account for different card content
Test URLs:
- After: https://home-cards--vitamix--aemsites.aem.network/us/en_us/
=> Home cards

blocks/banner/banner.css, blocks/banner/banner.js, styles/colors.css
new banner variant for homepage
Test URLs:
- After: https://home-banner--vitamix--aemsites.aem.network/us/en_us/
=> feat: home banner

blocks/pdp/pdp.js, scripts/minicart/cart.js
Test URLs:
- After: https://extended-warranty--vitamix--aemsites.aem.network/
=> fix: try entered options

blocks/collage/collage.css, blocks/collage/collage.js, styles/typography.css
Test URLs:
- After: https://collage--vitamix--aemsites.aem.network/us/en_us/
=> feat: collage block

blocks/pdp/pdp.js, scripts/storage/util.js
Test URLs:
- After: https://reset-cart--vitamix--aemsites.aem.network/
=> fix: hardcode store view into section load

styles/styles.css
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/why-vitamix
- After: https://site-width--vitamix--aemsites.aem.network/us/en_us/why-vitamix
=> fix: increase site width, remove bg color

blocks/pdp/options.js, blocks/pdp/pdp.js, blocks/pdp/specification-tabs.js
Test URLs:
- After: https://metadata-cleanup--vitamix--aemsites.aem.network/
=> fix: pull required data from jsonld rather than metadata

scripts/scripts.js, styles/styles.css
Test URLs:
- Before: 
https://main--vitamix--aemsites.aem.network/us/en_us/nav/nav
https://main--vitamix--aemsites.aem.network/us/en_us/nav/nav-banner
https://main--vitamix--aemsites.aem.network/us/en_us/footer/footer
https://main--vitamix--aemsites.aem.network/us/en_us/nav/modals/sign-up
https://main--vitamix--aemsites.aem.network/us/en_us/nav/modals/search
- After: https://fragment-preview--vitamix--aemsites.aem.network/us/en_us/nav/nav
https://fragment-preview--vitamix--aemsites.aem.network/us/en_us/nav/nav-banner
https://fragment-preview--vitamix--aemsites.aem.network/us/en_us/footer/footer
https://fragment-preview--vitamix--aemsites.aem.network/us/en_us/nav/modals/sign-up
https://fragment-preview--vitamix--aemsites.aem.network/us/en_us/nav/modals/search
=> Fragment preview

blocks/pdp/specification-tabs.js
- Before: 
https://main--vitamix--aemsites.aem.network/us/en_us/products/a2300-family-pack
https://main--vitamix--aemsites.aem.network/us/en_us/products/ascent-x2
https://main--vitamix--aemsites.aem.network/us/en_us/products/foodcycler-fc-50
https://main--vitamix--aemsites.aem.network/us/en_us/products/creations-ii
- After: 
https://warranty-tweak--vitamix--aemsites.aem.network/us/en_us/products/a2300-family-pack
https://warranty-tweak--vitamix--aemsites.aem.network/us/en_us/products/ascent-x2
https://warranty-tweak--vitamix--aemsites.aem.network/us/en_us/products/foodcycler-fc-50
https://warranty-tweak--vitamix--aemsites.aem.network/us/en_us/products/creations-ii
=> chore: updated warranty logic

blocks/pdp/specification-tabs.js
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/products/a2500-plus-aer-disc-container
- After: 
https://better-warranty--vitamix--aemsites.aem.network/us/en_us/products/a2500-plus-aer-disc-container
https://better-warranty--vitamix--aemsites.aem.network/us/en_us/products/e320
https://better-warranty--vitamix--aemsites.aem.network/us/en_us/products/ascent-x2
=> chore: better warranty handling for single lines

blocks/banner/banner.css, blocks/banner/banner.js
Test URLs:
- After: https://home-banner--vitamix--aemsites.aem.network/us/en_us/
- After: https://home-banner--vitamix--aemsites.aem.network/us/en_us/why-vitamix
=> fix: home banners

blocks/banner/banner.css, blocks/banner/banner.js, blocks/cards/cards.css, blocks/cards/cards.js
Test URLs:
- After: https://home-cards--vitamix--aemsites.aem.network/us/en_us/
=> fix: Home cards

blocks/carousel/carousel.css, blocks/carousel/carousel.js
Test URLs:
- After: https://home-carousel--vitamix--aemsites.aem.network/us/en_us/
=> feat: linked and buy-now variants

blocks/pdp/add-to-cart.js, blocks/pdp/pdp.css, blocks/pdp/pdp.js
Fix #154 
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/products/ascent-x2
- After: https://mobile-add-to-cart--vitamix--aemsites.aem.network/us/en_us/products/ascent-x2
=> feat: mobile add to cart layout

blocks/pdp/gallery.js
before: https://main--vitamix--aemsites.aem.network/us/en_us/products/foodcycler-fc-50
after: 
https://novariant-video--vitamix--aemsites.aem.network/us/en_us/products/foodcycler-fc-50
https://novariant-video--vitamix--aemsites.aem.network/us/en_us/products/ascent-x2
https://novariant-video--vitamix--aemsites.aem.network/us/en_us/products/ascent-x3
https://novariant-video--vitamix--aemsites.aem.network/us/en_us/products/ascent-x4
=> Novariant video

blocks/header/header.js, blocks/recommended-products/recommended-products.css, blocks/recommended-products/recommended-products.js, scripts/scripts.js, styles/styles.css
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/drafts/fkakatie/index-test
- After: https://rec-prod--vitamix--aemsites.aem.network/us/en_us/drafts/fkakatie/index-test
=> feat: recommended products block

scripts/consented.js
Test URLs:
- After: https://msft-ads-uet--vitamix--aemsites.aem.network/?martech=on
=> chore: add Microsoft Ads UET Tag

blocks/carousel/carousel.css, blocks/carousel/carousel.js
https://de-em-price--vitamix--aemsites.aem.network/us/en_us/drafts/campaign/
=> chore: de-emphasize price line

blocks/pdp/gallery.css, blocks/pdp/pdp.css, blocks/pdp/pdp.js, icons/x.svg
* adjust `pdp-alert` to green
* match eyebrow to existing style
* product name font changed to sentinel 
* swapped twitter logo to x logo
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/products/ascent-x5-smartprep-kitchen-system
- After: https://pdp-styles--vitamix--aemsites.aem.network/us/en_us/products/ascent-x5-smartprep-kitchen-system
=> fix: PDP styles

blocks/pdp/add-to-cart.js, blocks/pdp/options.js, blocks/pdp/pdp.js
Fix #169
Test URLs:
- After: https://fix-find-dealer--vitamix--aemsites.aem.network/
=> fix: logic around findLocally and findDealer

blocks/alert-banners/alert-banners.css, blocks/alert-banners/alert-banners.js, scripts/scripts.js
https://alert-banners--vitamix--aemsites.aem.network/us/en_us/products/ascent-x2
https://alert-banners--vitamix--aemsites.aem.page/us/en_us/nav/nav-banners?dapreview=on
=> Alert banners

scripts/scripts.js
Test URLs:
- After: https://set-affiliate-coupon--vitamix--aemsites.aem.network/
=> fix: set affiliate if found

blocks/pdp/pdp.js, blocks/pdp/pricing.js
Fix #125 
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/products/ascent-x2
- After: https://load-bv-earlier--vitamix--aemsites.aem.network/us/en_us/products/ascent-x2
=> chore: reduce delay for bv and affirm

package-lock.json, package.json
ref: https://github.com/aemsites/vitamix/security/dependabot/3
Test URLs:
- After: https://override-dep--vitamix--aemsites.aem.network/
=> chore: remove dependency

README.md, package.json, tests/pdp/integration.spec.js, tests/utils/test-helpers.js
Test URLs:
- After: https://newsletter-tests--vitamix--aemsites.aem.network/
=> chore: add tests for newsletter

blocks/pdp/add-to-cart.js, blocks/pdp/options.js
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/products/propel-series-510
- After: https://warranty-fix-3--vitamix--aemsites.aem.network/us/en_us/products/propel-series-510
=> fix: warranty tweak

package-lock.json, package.json, scripts/minicart/cart.js, tests/pdp/integration.spec.js
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/shop/ascent-x4?COUPON=test
- After: https://coupon--vitamix--aemsites.aem.network/us/en_us/shop/ascent-x4?COUPON=test
=> fix: legacy atc for coupon codes

blocks/pdp/pdp.css, blocks/pdp/pdp.js
allows to override About Features portion with a fragment authored in DA
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/products/ascent-and-venturist-series-tamper-holder
- After: https://features-fragment--vitamix--aemsites.aem.network/us/en_us/products/ascent-and-venturist-series-tamper-holder
=> chore: features fragment

scripts/scripts.js
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/products/5200-standard-getting-started
- After: https://loop-carousel--vitamix--aemsites.aem.network/us/en_us/products/5200-standard-getting-started
=> chore: add looping to carousel

blocks/pdp/add-to-cart.js
https://main--vitamix--aemsites.aem.network/us/en_us/products/a2300?color=red
https://fix-free-shipping--vitamix--aemsites.aem.network/us/en_us/products/a2300?color=red
=> chore: free shipping per variant

blocks/pdp/options.js, blocks/pdp/pdp.css, tests/pdp/integration.spec.js
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/us/en_us/products/a2300?color=red
- After: https://atc-variant--vitamix--aemsites.aem.network/us/en_us/products/a2300
=> fix: render but hide warranty selection on oos

blocks/cards/cards.css, blocks/columns/columns.css, blocks/columns/columns.js, styles/colors.css
icon list variant in columns
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/vr/en_us/household#distributors
- After: https://icon-list--vitamix--aemsites.aem.network/vr/en_us/household#distributors
=> feat: Icon list variant

blocks/cards/cards.css, styles/colors.css, styles/styles.css
a11y in overlay banners (esp dark variant)
Test URLs:
- Before: https://main--vitamix--aemsites.aem.network/vr/en_us/commercial#durability--precision-engineering
- After: https://overlay-banners--vitamix--aemsites.aem.network/vr/en_us/commercial#durability--precision-engineering
=> fix: Overlay banners
